<?xml version="1.0"?>
<package format="2">
  <version>1.0.0</version>
  <description>
    Semantic-Geometric Graph Descriptor (SGD) for robust LiDAR place recognition
    and loop closure detection.
  </description>

  <maintainer email="TODO@example.com">TODO</maintainer>
  <license>MIT</license>

  <url type="website">https://ieeexplore.ieee.org/abstract/document/11670325</url>

  <author>Z. Pan</author>
  <author>J. Hou</author>
  <author>L. Yu</author>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>cv_bridge</build_depend>
  <build_depend>libpcl-all-dev</build_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_export_depend>cv_bridge</build_export_depend>
  <build_export_depend>libpcl-all-dev</build_export_depend>
  <build_export_depend>roscpp</build_export_depend>
  <build_export_depend>rospy</build_export_depend>
  <build_export_depend>sensor_msgs</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <build_export_depend>tf_conversions</build_export_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>libpcl-all</exec_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>tf_conversions</exec_depend>

  <export>
  </export>
</package>
